version: '3'
services:
  simpleweb:
    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "3000:3000"
    volumes:
      - /apps/node_modules
      - .:/apps
  
  testweb:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /apps/node_modules
      - .:/apps

    command: ["npm", "run", "test"]